/*
 * JANGTQ Loader — read JANGTQ safetensors + sidecar runtime tensors.
 * Created by Jinho Jang (eric@jangq.ai)
 *
 * JANGTQ stores routed-expert MLP weights in three tensors per matrix:
 *
 *   "{base}.tq_packed" : uint32, shape (out, packed_in)  — codebook indices
 *   "{base}.tq_norms"  : float16, shape (out,)            — per-row L2 norm
 *   "{base}.tq_bits"   : uint8 / int32, scalar             — bit-width (2)
 *
 * For MoE models the per-expert tensors are stored at paths like:
 *
 *   model.layers.{L}.block_sparse_moe.experts.{E}.w1.tq_packed   (gate)
 *   model.layers.{L}.block_sparse_moe.experts.{E}.w2.tq_packed   (down)
 *   model.layers.{L}.block_sparse_moe.experts.{E}.w3.tq_packed   (up)
 *
 * The loader stacks them along axis 0 into 3D tensors per (layer, projection):
 *
 *   model.layers.{L}.block_sparse_moe.switch_mlp.gate_proj.{packed,norms}
 *   model.layers.{L}.block_sparse_moe.switch_mlp.up_proj.{packed,norms}
 *   model.layers.{L}.block_sparse_moe.switch_mlp.down_proj.{packed,norms}
 *
 * Naming variants handled (matches Python `load_jangtq.py` regex):
 *   - GLM 5.1     : model.layers.L.mlp.experts.E.{gate_proj,up_proj,down_proj}
 *   - MiniMax M2.7: model.layers.L.block_sparse_moe.experts.E.{w1,w2,w3}
 *                   (Mixtral convention: w1=gate, w2=down, w3=up)
 *
 * SIGNS AND CODEBOOK — runtime sidecar
 * ────────────────────────────────────
 * The Hadamard signs and 2-bit codebooks are NOT stored in the main
 * safetensors shards. They are deterministic functions of (in_features,
 * seed) and (in_features, bits) respectively, computed at quantization
 * time via NumPy's PCG64 + Lloyd-Max iteration.
 *
 * Re-deriving them in Swift requires bit-exact PCG64 + Lloyd-Max —
 * possible but error-prone. Cleaner approach: ship a sidecar safetensors
 * file `jangtq_runtime.safetensors` next to the model that contains:
 *
 *   "signs.{in_features}.{seed}"      : float32, shape (in_features,)
 *   "codebook.{in_features}.{bits}"   : float32, shape (2^bits,)
 *
 * Generated by `jang-tools/scripts/export_jangtq_runtime.py` (see
 * Python side). The Swift loader looks for this file; if absent it
 * raises an error directing the user to run the export script.
 */

import Foundation
import Metal

/// One MLX-format affine quantized weight matrix.
///
/// Used for the non-MoE weights in a JANGTQ model: attention projections
/// (q/k/v/o), embed_tokens, lm_head. Each of these is stored as a standard
/// `nn.QuantizedLinear` triplet:
///
///   weight : uint32, shape (out_features, in_features / vals_per_u32)
///   scales : float16, shape (out_features, in_features / group_size)
///   biases : float16, same shape as scales
///
/// where `vals_per_u32 = 32 / bits`. All three live as `MTLBuffer` for
/// direct Metal kernel dispatch.
public struct JANGTQAffineWeight: @unchecked Sendable {
    public let basePath: String          // e.g. "model.layers.0.self_attn.q_proj"
    public let bits: Int                  // 8 for attention/embed/lm_head
    public let groupSize: Int             // typically 64
    public let inFeatures: Int
    public let outFeatures: Int
    public let qweight: MTLBuffer         // (out, in/vals_per_u32) uint32
    public let scales: MTLBuffer          // (out, in/group_size) half
    public let biases: MTLBuffer          // same shape as scales
}

/// One JANGTQ-quantized weight matrix (or stack of matrices for MoE experts).
///
/// `@unchecked Sendable` because `MTLBuffer` is a Metal protocol that doesn't
/// declare Sendable conformance even though buffers in shared storage mode
/// are safe to read from multiple threads. Callers must not mutate buffer
/// contents from multiple threads concurrently.
public struct JANGTQWeight: @unchecked Sendable {
    public let basePath: String      // e.g. "model.layers.5.block_sparse_moe.switch_mlp.gate_proj"
    public let bits: Int             // 2 for routed_expert, 8 for attention/embed/lm_head

    /// Packed uint32 buffer. Shape:
    ///   per-expert dense:    (out_features, packed_in)
    ///   stacked switch_mlp:  (n_experts, out_features, packed_in)
    public let packed: MTLBuffer
    public let packedShape: [Int]
    public let logicalInFeatures: Int?

    /// Per-row norms (float16). Shape:
    ///   per-expert dense:    (out_features,)
    ///   stacked switch_mlp:  (n_experts, out_features)
    public let norms: MTLBuffer
    public let normsShape: [Int]

    public var isStacked: Bool { packedShape.count == 3 }
    public var nExperts: Int { isStacked ? packedShape[0] : 1 }
    public var outFeatures: Int { isStacked ? packedShape[1] : packedShape[0] }
    public var inFeatures: Int {
        logicalInFeatures ?? (isStacked ? packedShape[2] : packedShape[1]) * (32 / bits)
    }
}

/// Loaded JANGTQ runtime sidecar — signs + codebooks indexed by their cache key.
public struct JANGTQRuntimeSidecar: @unchecked Sendable {
    /// Hadamard signs for a given `(in_features, seed)` pair.
    /// Shape: (in_features,) float32 ±1.
    public let signs: [String: MTLBuffer]

    /// Lloyd-Max codebook for a given `(in_features, bits)` pair.
    /// Shape: (2^bits,) float32.
    public let codebooks: [String: MTLBuffer]

    public static func signsKey(inFeatures: Int, seed: Int) -> String {
        "signs.\(inFeatures).\(seed)"
    }

    public static func codebookKey(inFeatures: Int, bits: Int) -> String {
        "codebook.\(inFeatures).\(bits)"
    }

    public func signs(inFeatures: Int, seed: Int) throws -> MTLBuffer {
        let key = JANGTQRuntimeSidecar.signsKey(inFeatures: inFeatures, seed: seed)
        guard let buf = signs[key] else {
            throw JANGError.tensorNotFound("sidecar missing \(key)")
        }
        return buf
    }

    public func codebook(inFeatures: Int, bits: Int) throws -> MTLBuffer {
        let key = JANGTQRuntimeSidecar.codebookKey(inFeatures: inFeatures, bits: bits)
        guard let buf = codebooks[key] else {
            throw JANGError.tensorNotFound("sidecar missing \(key)")
        }
        return buf
    }
}

/// Result of loading a JANGTQ model directory.
public struct JANGTQModelBundle: @unchecked Sendable {
    public let config: JANGModelConfig

    /// All TQ-quantized weights, keyed by base path. Includes both
    /// per-expert (dense path) and stacked switch_mlp tensors.
    public let weights: [String: JANGTQWeight]

    /// MLX-format affine quantized weights — attention projections,
    /// embed_tokens, lm_head, per-layer norms (kept as half buffers on
    /// the side, see `normWeights`).
    public let affineWeights: [String: JANGTQAffineWeight]

    /// Plain half-precision tensors (norms, router gate, embedding bias, …).
    /// Stored as MTLBuffer for direct kernel use.
    public let halfTensors: [String: MTLBuffer]

    /// Runtime sidecar — signs and codebooks needed by the kernels.
    public let sidecar: JANGTQRuntimeSidecar

    /// Number of experts that were stacked into 3D switch_mlp tensors.
    public let nStackedGroups: Int
}

/// Loads JANGTQ models from a directory. Walks all `.safetensors` shards,
/// groups TQ tensors by base path, stacks per-expert tensors, and produces
/// `MTLBuffer`s ready for the JANGTQ kernels.
public final class JANGTQLoader {
    public let device: MTLDevice

    public init(device: MTLDevice) {
        self.device = device
    }

    public func load(from directory: URL) throws -> JANGTQModelBundle {
        // 1. Parse config
        let config = try JANGModelConfig.load(from: directory)
        guard config.quant.format == .mxtq else {
            throw JANGError.invalidFormat(
                "JANGTQLoader requires weight_format='mxtq', got '\(config.quant.format)'"
            )
        }

        // 2. Walk all safetensors shards, collect tq_packed / tq_norms / tq_bits
        // (TQ-quantized) AND .weight / .scales / .biases (MLX affine 8-bit) AND
        // standalone half tensors (norms, gate, etc.).
        let shards = try loadSafetensorsShards(from: directory)
        let shouldShiftQwenNormWeights = Self.shouldShiftQwenNormWeights(
            config: config,
            shards: shards
        )

        // TQ pending (per-expert)
        var pendingPacked: [String: (file: SafetensorsFile, info: TensorInfo)] = [:]
        var pendingNorms:  [String: (file: SafetensorsFile, info: TensorInfo)] = [:]
        var pendingBits:   [String: Int] = [:]
        var pendingInFeatures: [String: Int] = [:]

        // Affine 8-bit pending
        var pendingAW: [String: (file: SafetensorsFile, info: TensorInfo)] = [:]
        var pendingAS: [String: (file: SafetensorsFile, info: TensorInfo)] = [:]
        var pendingAB: [String: (file: SafetensorsFile, info: TensorInfo)] = [:]

        // Half tensors (norms, gate weights, e_score_correction_bias, etc.)
        var halfBuffers: [String: MTLBuffer] = [:]

        for shard in shards {
            for (name, info) in shard.tensors {
                if name.hasSuffix(".tq_packed") {
                    let base = String(name.dropLast(".tq_packed".count))
                    pendingPacked[base] = (shard, info)
                } else if name.hasSuffix(".tq_norms") {
                    let base = String(name.dropLast(".tq_norms".count))
                    pendingNorms[base] = (shard, info)
                } else if name.hasSuffix(".tq_bits") {
                    let base = String(name.dropLast(".tq_bits".count))
                    let data = try shard.tensorData(name: name)
                    var bitsValue: Int = 2
                    if info.dtype == "U8" || info.dtype == "I8" {
                        bitsValue = Int(data.first ?? 2)
                    } else if info.dtype == "I32" || info.dtype == "U32" {
                        bitsValue = data.withUnsafeBytes { raw in
                            Int(raw.load(as: Int32.self))
                        }
                    } else if info.dtype == "I64" || info.dtype == "U64" {
                        bitsValue = data.withUnsafeBytes { raw in
                            Int(raw.load(as: Int64.self))
                        }
                    }
                    pendingBits[base] = bitsValue
                } else if name.hasSuffix(".tq_in_features") {
                    let base = String(name.dropLast(".tq_in_features".count))
                    let data = try shard.tensorData(name: name)
                    var inFeaturesValue: Int = 0
                    if info.dtype == "U8" || info.dtype == "I8" {
                        inFeaturesValue = Int(data.first ?? 0)
                    } else if info.dtype == "I32" || info.dtype == "U32" {
                        inFeaturesValue = data.withUnsafeBytes { raw in
                            Int(raw.load(as: Int32.self))
                        }
                    } else if info.dtype == "I64" || info.dtype == "U64" {
                        inFeaturesValue = data.withUnsafeBytes { raw in
                            Int(raw.load(as: Int64.self))
                        }
                    }
                    if inFeaturesValue > 0 {
                        pendingInFeatures[base] = inFeaturesValue
                    }
                } else if name.hasSuffix(".weight") && info.dtype == "U32" {
                    let base = String(name.dropLast(".weight".count))
                    pendingAW[base] = (shard, info)
                } else if name.hasSuffix(".scales") && (info.dtype == "F16" || info.dtype == "BF16") {
                    let base = String(name.dropLast(".scales".count))
                    pendingAS[base] = (shard, info)
                } else if name.hasSuffix(".biases") && (info.dtype == "F16" || info.dtype == "BF16") {
                    let base = String(name.dropLast(".biases".count))
                    pendingAB[base] = (shard, info)
                } else if info.dtype == "F16" || info.dtype == "BF16" {
                    // Plain half tensor (norms, gate Linear weight, etc.)
                    if shouldShiftQwenNormWeights,
                       Self.isQwenShiftedNormTensor(name: name, info: info) {
                        halfBuffers[name] = try Self.makeShiftedHalfBuffer(
                            shard: shard,
                            name: name,
                            info: info,
                            device: device,
                            delta: 1.0
                        )
                    } else {
                        halfBuffers[name] = try shard.makeMetalBuffer(name: name, device: device)
                    }
                }
            }
        }

        // 3. Group per-expert tensors and stack into 3D switch_mlp tensors.
        // Four naming conventions are accepted via optional VLM/TextModel prefix:
        //   - model.layers.L...                    (MiniMax / GLM / plain)
        //   - model.language_model.layers.L...     (raw HF Qwen3.5/3.6 VLM)
        //   - language_model.model.layers.L...     (post-sanitize Qwen3.5/3.6)
        //   - language_model.layers.L...           (rare; some Qwen text-only paths)
        //
        // Note: Qwen3.5/3.6 JANGTQ shards converted with `convert_qwen35_jangtq.py`
        // come PRE-STACKED (3D `switch_mlp.{gate,up,down}_proj.tq_packed`) and so
        // fall through to `residualBases` below — no stacking needed. The regex
        // path here remains for GLM/MiniMax per-expert inputs.
        let _vlmPrefix = #"(?:model\.language_model\.|language_model\.model\.|language_model\.|model\.)"#
        let glmRegex = try NSRegularExpression(
            pattern: #"^(\#(_vlmPrefix)layers\.\d+\.mlp\.)experts\.(\d+)\.(gate_proj|up_proj|down_proj)$"#
        )
        let mmRegex = try NSRegularExpression(
            pattern: #"^(\#(_vlmPrefix)layers\.\d+\.block_sparse_moe\.)experts\.(\d+)\.(w[123])$"#
        )
        let mmProjMap: [String: String] = ["w1": "gate_proj", "w2": "down_proj", "w3": "up_proj"]

        // (layer_prefix, proj_name) -> {expert_id: base_path}
        var expertGroups: [GroupKey: [Int: String]] = [:]

        var residualBases: [String] = []  // bases that are NOT expert tensors (attention etc.)
        for base in pendingPacked.keys {
            let nsBase = base as NSString
            let range = NSRange(location: 0, length: nsBase.length)

            if let m = glmRegex.firstMatch(in: base, range: range), m.numberOfRanges == 4 {
                let layerPrefix = nsBase.substring(with: m.range(at: 1))
                let expertID = Int(nsBase.substring(with: m.range(at: 2)))!
                let projName = nsBase.substring(with: m.range(at: 3))
                let key = GroupKey(prefix: layerPrefix, proj: projName)
                expertGroups[key, default: [:]][expertID] = base
                continue
            }
            if let m = mmRegex.firstMatch(in: base, range: range), m.numberOfRanges == 4 {
                let layerPrefix = nsBase.substring(with: m.range(at: 1))
                let expertID = Int(nsBase.substring(with: m.range(at: 2)))!
                let wName = nsBase.substring(with: m.range(at: 3))
                guard let projName = mmProjMap[wName] else { continue }
                let key = GroupKey(prefix: layerPrefix, proj: projName)
                expertGroups[key, default: [:]][expertID] = base
                continue
            }
            residualBases.append(base)
        }

        var weights: [String: JANGTQWeight] = [:]

        func inferredLogicalInFeatures(base: String, proj: String? = nil) -> Int? {
            if let explicit = pendingInFeatures[base] {
                return explicit
            }
            let model = config.model
            let projection = proj ?? {
                if base.hasSuffix(".gate_proj") { return "gate_proj" }
                if base.hasSuffix(".up_proj") { return "up_proj" }
                if base.hasSuffix(".down_proj") { return "down_proj" }
                return ""
            }()
            guard base.contains(".switch_mlp.") || base.contains(".experts.") else {
                return nil
            }
            if projection == "gate_proj" || projection == "up_proj" || projection == "w1" || projection == "w3" {
                return model.hiddenSize > 0 ? model.hiddenSize : nil
            }
            if projection == "down_proj" || projection == "w2" {
                let intermediate = model.moeIntermediateSize ?? model.intermediateSize
                return intermediate > 0 ? intermediate : nil
            }
            return nil
        }

        // 4. Build stacked switch_mlp tensors
        for (key, experts) in expertGroups {
            let nExperts = (experts.keys.max() ?? -1) + 1
            guard nExperts > 0 else { continue }
            // All experts must exist for this layer
            var packedShards: [(SafetensorsFile, TensorInfo)] = []
            var normsShards:  [(SafetensorsFile, TensorInfo)] = []
            var bitsValue = 2
            for e in 0..<nExperts {
                guard let base = experts[e],
                      let p = pendingPacked[base],
                      let n = pendingNorms[base] else {
                    throw JANGError.invalidFormat(
                        "expert group \(key.prefix)\(key.proj) missing expert \(e)"
                    )
                }
                packedShards.append(p)
                normsShards.append(n)
                if let b = pendingBits[base] { bitsValue = b }
            }

            // Concatenate the packed shards. Each per-expert packed has shape
            // (out_features, packed_in). After stacking we want
            // (n_experts, out_features, packed_in).
            let firstPackedInfo = packedShards[0].1
            precondition(firstPackedInfo.shape.count == 2,
                "expected per-expert packed shape (out, packed_in), got \(firstPackedInfo.shape)")
            let outFeatures = firstPackedInfo.shape[0]
            let packedIn = firstPackedInfo.shape[1]
            let packedRowBytes = outFeatures * packedIn * MemoryLayout<UInt32>.stride
            let packedTotalBytes = packedRowBytes * nExperts
            guard let packedBuf = device.makeBuffer(length: packedTotalBytes, options: .storageModeShared) else {
                throw JANGError.bufferAllocationFailed(packedTotalBytes)
            }
            for (e, (shard, info)) in packedShards.enumerated() {
                let src = try shard.tensorData(name: experts[e]! + ".tq_packed")
                precondition(src.count == packedRowBytes,
                    "expert \(e) packed bytes \(src.count) != \(packedRowBytes)")
                let dstPtr = packedBuf.contents().advanced(by: e * packedRowBytes)
                _ = src.withUnsafeBytes { srcRaw -> Int in
                    memcpy(dstPtr, srcRaw.baseAddress!, packedRowBytes)
                    return 0
                }
                _ = info  // silence unused
            }

            // Stack norms similarly. Per-expert (out_features,) f16 → (n_experts, out_features) f16.
            let normsRowBytes = outFeatures * MemoryLayout<Float16>.stride
            let normsTotalBytes = normsRowBytes * nExperts
            guard let normsBuf = device.makeBuffer(length: normsTotalBytes, options: .storageModeShared) else {
                throw JANGError.bufferAllocationFailed(normsTotalBytes)
            }
            for (e, (shard, _)) in normsShards.enumerated() {
                let src = try shard.tensorData(name: experts[e]! + ".tq_norms")
                precondition(src.count == normsRowBytes,
                    "expert \(e) norms bytes \(src.count) != \(normsRowBytes)")
                let dstPtr = normsBuf.contents().advanced(by: e * normsRowBytes)
                _ = src.withUnsafeBytes { srcRaw -> Int in
                    memcpy(dstPtr, srcRaw.baseAddress!, normsRowBytes)
                    return 0
                }
            }

            let stackedBase = "\(key.prefix)switch_mlp.\(key.proj)"
            weights[stackedBase] = JANGTQWeight(
                basePath: stackedBase,
                bits: bitsValue,
                packed: packedBuf,
                packedShape: [nExperts, outFeatures, packedIn],
                logicalInFeatures: inferredLogicalInFeatures(base: stackedBase, proj: key.proj),
                norms: normsBuf,
                normsShape: [nExperts, outFeatures]
            )
        }

        // 5. Non-expert TQ weights (if any) — just copy through as 2D
        for base in residualBases {
            guard let p = pendingPacked[base], let n = pendingNorms[base] else { continue }
            let bits = pendingBits[base] ?? 2
            let packedBuf = try p.file.makeMetalBuffer(name: base + ".tq_packed", device: device)
            let normsBuf  = try n.file.makeMetalBuffer(name: base + ".tq_norms",  device: device)
            weights[base] = JANGTQWeight(
                basePath: base,
                bits: bits,
                packed: packedBuf,
                packedShape: p.info.shape,
                logicalInFeatures: inferredLogicalInFeatures(base: base),
                norms: normsBuf,
                normsShape: n.info.shape
            )
        }

        // 6. Build affine 8-bit weights from the (.weight, .scales, .biases) triplets.
        // group_size is fixed to 64 in the JANGTQ converter (matches mxtq config).
        let groupSize = config.quant.mxtqGroupSize > 0 ? config.quant.mxtqGroupSize : 64
        var affineWeights: [String: JANGTQAffineWeight] = [:]
        for (base, w) in pendingAW {
            guard let s = pendingAS[base], let b = pendingAB[base] else {
                // Missing scales/biases — not actually a quantized linear, skip.
                continue
            }
            // Determine bits from shapes:
            //   weight.shape  = (out, in / vals_per_u32)
            //   scales.shape  = (out, in / group_size)
            // Therefore: vals_per_u32 = (s.shape[1] * group_size) / w.shape[1]
            //            bits         = 32 / vals_per_u32
            guard w.info.shape.count == 2, s.info.shape.count == 2 else { continue }
            let outF   = w.info.shape[0]
            let wCols  = w.info.shape[1]
            let sCols  = s.info.shape[1]
            let inFeat = sCols * groupSize
            // vals_per_u32 = inFeat / wCols
            guard wCols > 0, inFeat % wCols == 0 else { continue }
            let valsPerU32 = inFeat / wCols
            guard valsPerU32 > 0, 32 % valsPerU32 == 0 else { continue }
            let bits = 32 / valsPerU32

            let qBuf = try w.file.makeMetalBuffer(name: base + ".weight", device: device)
            let sBuf = try s.file.makeMetalBuffer(name: base + ".scales", device: device)
            let bBuf = try b.file.makeMetalBuffer(name: base + ".biases", device: device)

            affineWeights[base] = JANGTQAffineWeight(
                basePath: base,
                bits: bits,
                groupSize: groupSize,
                inFeatures: inFeat,
                outFeatures: outF,
                qweight: qBuf,
                scales: sBuf,
                biases: bBuf
            )
        }

        // 7. Load the runtime sidecar (signs + codebooks)
        let sidecar = try loadRuntimeSidecar(directory: directory)

        return JANGTQModelBundle(
            config: config,
            weights: weights,
            affineWeights: affineWeights,
            halfTensors: halfBuffers,
            sidecar: sidecar,
            nStackedGroups: expertGroups.count
        )
    }

    /// Load `jangtq_runtime.safetensors` from the model directory.
    /// Tensors are keyed `signs.{in_features}.{seed}` and `codebook.{in_features}.{bits}`.
    public func loadRuntimeSidecar(directory: URL) throws -> JANGTQRuntimeSidecar {
        let url = directory.appendingPathComponent("jangtq_runtime.safetensors")
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw JANGError.modelNotFound(
                "jangtq_runtime.safetensors not found in \(directory.path) — " +
                "run jang-tools/scripts/export_jangtq_runtime.py to generate it"
            )
        }
        let file = try SafetensorsFile(url: url)
        var signs: [String: MTLBuffer] = [:]
        var codebooks: [String: MTLBuffer] = [:]
        for (name, _) in file.tensors {
            if name.hasPrefix("signs.") {
                signs[name] = try file.makeMetalBuffer(name: name, device: device)
            } else if name.hasPrefix("codebook.") {
                codebooks[name] = try file.makeMetalBuffer(name: name, device: device)
            }
        }
        return JANGTQRuntimeSidecar(signs: signs, codebooks: codebooks)
    }

    // MARK: - Internal grouping key

    private struct GroupKey: Hashable {
        let prefix: String
        let proj: String
    }

    private static func shouldShiftQwenNormWeights(
        config: JANGModelConfig,
        shards: [SafetensorsFile]
    ) -> Bool {
        let modelType = config.model.modelType?.lowercased() ?? ""
        let architecture = config.model.architectures?.joined(separator: " ").lowercased() ?? ""
        let isQwenHybrid = modelType.contains("qwen3_5")
            || modelType.contains("qwen3_next")
            || architecture.contains("qwen3_5")
            || architecture.contains("qwen3next")
        guard isQwenHybrid else { return false }

        for shard in shards {
            for (name, info) in shard.tensors {
                if name.contains("mtp.") {
                    return true
                }
                if name.contains("conv1d.weight"),
                   let last = info.shape.last,
                   last != 1 {
                    return true
                }
            }
        }
        return false
    }

    private static func isQwenShiftedNormTensor(name: String, info: TensorInfo) -> Bool {
        guard info.shape.count == 1 else { return false }
        let suffixes = [
            ".input_layernorm.weight",
            ".post_attention_layernorm.weight",
            "model.norm.weight",
            ".q_norm.weight",
            ".k_norm.weight",
        ]
        return suffixes.contains { name.hasSuffix($0) }
    }

    private static func makeShiftedHalfBuffer(
        shard: SafetensorsFile,
        name: String,
        info: TensorInfo,
        device: MTLDevice,
        delta: Float
    ) throws -> MTLBuffer {
        let count = info.shape.reduce(1, *)
        let outBytes = count * MemoryLayout<Float16>.stride
        guard let buffer = device.makeBuffer(length: outBytes, options: .storageModeShared) else {
            throw JANGError.bufferAllocationFailed(outBytes)
        }
        let dst = buffer.contents().bindMemory(to: Float16.self, capacity: count)
        let data = try shard.tensorData(name: name)
        try data.withUnsafeBytes { raw in
            if info.dtype == "F16" {
                let src = raw.bindMemory(to: Float16.self)
                guard src.count >= count else {
                    throw JANGError.safetensorsError("Tensor \(name) is shorter than expected")
                }
                for i in 0..<count {
                    dst[i] = Float16(Float(src[i]) + delta)
                }
            } else if info.dtype == "BF16" {
                let src = raw.bindMemory(to: UInt16.self)
                guard src.count >= count else {
                    throw JANGError.safetensorsError("Tensor \(name) is shorter than expected")
                }
                for i in 0..<count {
                    let bits = UInt32(src[i]) << 16
                    let value = Float(bitPattern: bits)
                    dst[i] = Float16(value + delta)
                }
            } else {
                throw JANGError.invalidFormat("Cannot shift non-half tensor \(name) dtype=\(info.dtype)")
            }
        }
        return buffer
    }
}
