"""Intent Prune helpers: transitions, path graph, hybrid_v1 scoring.

PR-IP0: transition emission + adjacency building.
PR-IP1: power-iteration path scores + hybrid fusion + plan emit.
"""

from .graph import (
    build_row_stochastic,
    build_sparse_operator,
    decode_node,
    mass_has_signal,
    mass_matrix_from_adjacency,
    node_id,
    path_scores_from_transitions,
    power_iteration,
    power_iteration_sparse,
    stationary_from_adjacency,
)
from .score import (
    BALANCED_WEIGHTS,
    HIGHWAY_E,
    HIGHWAY_H,
    HIGHWAY_L,
    HIGHWAY_N,
    PLAN_SCHEMA,
    PRESET_WEIGHTS,
    SAFETY_STANCES,
    SCORER_NAME,
    SPECIALIST_WEIGHTS,
    HybridScoreResult,
    build_prune_plan,
    build_synthetic_highway_records,
    filter_records_for_intents,
    filter_records_for_safety,
    fusion_score_layer,
    mass_only_scores,
    norm_layer,
    resolve_weights,
    score_hybrid,
    score_transitions_to_plan,
    select_keep_k,
    write_prune_plan,
)
from .transitions import (
    ADJACENCY_SCHEMA,
    CRACK_PROBE_MARKERS,
    SAFETY_PROBE_MARKERS,
    TRANSITION_SCHEMA,
    build_adjacency_from_transitions,
    build_transition_records,
    iter_transition_records,
    path_from_token_trace,
    prompt_transition_meta,
    transitions_from_generation_row,
    transitions_from_generations_jsonl,
    write_adjacency_json,
    write_transitions_jsonl,
)

__all__ = [
    # transitions
    "ADJACENCY_SCHEMA",
    "CRACK_PROBE_MARKERS",
    "SAFETY_PROBE_MARKERS",
    "TRANSITION_SCHEMA",
    "build_adjacency_from_transitions",
    "build_transition_records",
    "iter_transition_records",
    "path_from_token_trace",
    "prompt_transition_meta",
    "transitions_from_generation_row",
    "transitions_from_generations_jsonl",
    "write_adjacency_json",
    "write_transitions_jsonl",
    # graph
    "build_row_stochastic",
    "build_sparse_operator",
    "decode_node",
    "mass_has_signal",
    "mass_matrix_from_adjacency",
    "node_id",
    "path_scores_from_transitions",
    "power_iteration",
    "power_iteration_sparse",
    "stationary_from_adjacency",
    # score
    "BALANCED_WEIGHTS",
    "HIGHWAY_E",
    "HIGHWAY_H",
    "HIGHWAY_L",
    "HIGHWAY_N",
    "PLAN_SCHEMA",
    "PRESET_WEIGHTS",
    "SAFETY_STANCES",
    "SCORER_NAME",
    "SPECIALIST_WEIGHTS",
    "HybridScoreResult",
    "build_prune_plan",
    "build_synthetic_highway_records",
    "filter_records_for_intents",
    "filter_records_for_safety",
    "fusion_score_layer",
    "mass_only_scores",
    "norm_layer",
    "resolve_weights",
    "score_hybrid",
    "score_transitions_to_plan",
    "select_keep_k",
    "write_prune_plan",
]
