"""Intent Prune helpers: transitions, path graph, hybrid_v1 scoring, CRACK pack.

PR-IP0: transition emission + adjacency building.
PR-IP1: power-iteration path scores + hybrid fusion + plan emit.
PR-IP2: CRACK probe pack assets, fingerprint, metrics, naming.
"""

from .crack import (
    CRACK_CLASSES,
    CRACK_PACK_FILENAME,
    CRACK_PACK_NAME,
    CRACK_PACK_VERSION,
    CRACK_STANCE,
    CRACK_SUFFIX,
    MAX_CRACK_PROBES,
    MIN_CRACK_PROBES,
    MIN_STILL_REFUSE_ANCHORS,
    apply_crack_suffix,
    content_sha256,
    crack_pack_fingerprint,
    crack_pack_meta,
    crack_pack_name_for_path,
    default_crack_pack_path,
    file_sha256,
    has_crack_suffix,
    intent_prune_artifact_name,
    is_crack_stance,
    join_intent_slugs,
    load_crack_pack,
    normalize_crack_class,
    normalize_intent_slug,
    resolve_crack_pack_for_plan,
)
from .graph import (
    build_row_stochastic,
    build_sparse_operator,
    decode_node,
    mass_has_signal,
    mass_matrix_from_adjacency,
    node_id,
    path_scores_from_transitions,
    power_iteration,
    power_iteration_sparse,
    stationary_from_adjacency,
)
from .metrics import (
    RESPONSE_LABELS,
    aggregate_crack_metrics,
    classify_response,
    crack_eval_gate,
    crack_metrics_delta,
    is_refusal,
    is_refusal_or_partial,
    score_crack_eval_row,
    score_crack_pack_responses,
)
from .score import (
    BALANCED_WEIGHTS,
    DEFAULT_PRESET,
    DEFAULT_SAFETY_STANCE,
    HIGHWAY_E,
    HIGHWAY_H,
    HIGHWAY_L,
    HIGHWAY_N,
    PLAN_SCHEMA,
    PRESET_WEIGHTS,
    SAFETY_STANCES,
    SCORER_NAME,
    SPECIALIST_WEIGHTS,
    HybridScoreResult,
    build_prune_plan,
    build_synthetic_highway_records,
    filter_records_for_intents,
    filter_records_for_safety,
    fusion_score_layer,
    mass_only_scores,
    norm_layer,
    resolve_weights,
    score_hybrid,
    score_transitions_to_plan,
    select_keep_k,
    write_prune_plan,
)
from .transitions import (
    ADJACENCY_SCHEMA,
    CRACK_PROBE_MARKERS,
    SAFETY_PROBE_MARKERS,
    TRANSITION_SCHEMA,
    build_adjacency_from_transitions,
    build_transition_records,
    iter_transition_records,
    path_from_token_trace,
    prompt_transition_meta,
    transitions_from_generation_row,
    transitions_from_generations_jsonl,
    write_adjacency_json,
    write_transitions_jsonl,
)

__all__ = [
    # transitions
    "ADJACENCY_SCHEMA",
    "CRACK_PROBE_MARKERS",
    "SAFETY_PROBE_MARKERS",
    "TRANSITION_SCHEMA",
    "build_adjacency_from_transitions",
    "build_transition_records",
    "iter_transition_records",
    "path_from_token_trace",
    "prompt_transition_meta",
    "transitions_from_generation_row",
    "transitions_from_generations_jsonl",
    "write_adjacency_json",
    "write_transitions_jsonl",
    # graph
    "build_row_stochastic",
    "build_sparse_operator",
    "decode_node",
    "mass_has_signal",
    "mass_matrix_from_adjacency",
    "node_id",
    "path_scores_from_transitions",
    "power_iteration",
    "power_iteration_sparse",
    "stationary_from_adjacency",
    # score
    "BALANCED_WEIGHTS",
    "DEFAULT_PRESET",
    "DEFAULT_SAFETY_STANCE",
    "HIGHWAY_E",
    "HIGHWAY_H",
    "HIGHWAY_L",
    "HIGHWAY_N",
    "PLAN_SCHEMA",
    "PRESET_WEIGHTS",
    "SAFETY_STANCES",
    "SCORER_NAME",
    "SPECIALIST_WEIGHTS",
    "HybridScoreResult",
    "build_prune_plan",
    "build_synthetic_highway_records",
    "filter_records_for_intents",
    "filter_records_for_safety",
    "fusion_score_layer",
    "mass_only_scores",
    "norm_layer",
    "resolve_weights",
    "score_hybrid",
    "score_transitions_to_plan",
    "select_keep_k",
    "write_prune_plan",
    # crack pack + naming
    "CRACK_CLASSES",
    "CRACK_PACK_FILENAME",
    "CRACK_PACK_NAME",
    "CRACK_PACK_VERSION",
    "CRACK_STANCE",
    "CRACK_SUFFIX",
    "MAX_CRACK_PROBES",
    "MIN_CRACK_PROBES",
    "MIN_STILL_REFUSE_ANCHORS",
    "apply_crack_suffix",
    "content_sha256",
    "crack_pack_fingerprint",
    "crack_pack_meta",
    "crack_pack_name_for_path",
    "default_crack_pack_path",
    "file_sha256",
    "has_crack_suffix",
    "intent_prune_artifact_name",
    "is_crack_stance",
    "join_intent_slugs",
    "load_crack_pack",
    "normalize_crack_class",
    "normalize_intent_slug",
    "resolve_crack_pack_for_plan",
    # metrics
    "RESPONSE_LABELS",
    "aggregate_crack_metrics",
    "classify_response",
    "crack_eval_gate",
    "crack_metrics_delta",
    "is_refusal",
    "is_refusal_or_partial",
    "score_crack_eval_row",
    "score_crack_pack_responses",
]
